//axios cria e consome a api
import axios from 'axios';

export const oracleApi = axios.create({
  baseURL: 'https://gbe9f5772edc850-weatherbd.adb.sa-saopaulo-1.oraclecloudapps.com/ords/admin/weathersearch',

  //Doc da paginação da oracle
  //https://docs.oracle.com/en/cloud/saas/service/18a/cxsvc/c_osvc_pagination.html
});

/*
Script SQL
CREATE TABLE tb_weatherSearch(
    cod_weatherSearch INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    cidade VARCHAR2(200) NOT NULL,
    dataHora TIMESTAMP NOT NULL
);
*/